Droptimizers
mist-guild/mist-tyrhold pull request #12
Opened 2023-01-11 02:10 UTC by Bkrenz

Translated Droptimizer Aggregator code to Bot.
Started parceling to Services and Utilities.
Added Search feature and command.

2023-01-11 23:21 UTC, zakpruitt requested changes
picked up this review from yesterday, but just organization and some optimization, then we're good :) i am going to work on some commit that you can then review.

2023-01-11 23:21 UTC, zakpruitt commented on modules/cogs/droptimizer_cog.py
> +            concat = pandas.concat([max_val, max_item], axis=1)
we can optimize this logic, it'll be in a seperate commit

2023-01-11 23:21 UTC, zakpruitt commented on modules/utility/blizzard_utility.py
> +}
This can all be moved into a JSON folder or something

2023-01-11 23:21 UTC, zakpruitt commented on modules/utility/blizzard_utility.py
> +            '-44': 'Trash',
what is -44?

2023-01-11 23:21 UTC, zakpruitt commented on modules/utility/blizzard_utility.py
> +        self.item_list = cache['item']
After thinking on it, we should probably move the BLizzardUtility to the /api/ folders and create the dependencies/any data classes we need there.

2023-01-11 23:30 UTC, Bkrenz commented on modules/cogs/droptimizer_cog.py
> +    @commands.command(name="droptimizer_run")
I think I tried running it once as 'droptimizer run' and it wouldn't work, so I changed it. Would be open to it, just couldn't find any quick examples and was a minor issue.

2023-01-11 23:30 UTC, Bkrenz commented on modules/cogs/droptimizer_cog.py
> +        self.sheets_util.write_data_to_worksheet('Summary', pandas.DataFrame(data=normal_summary).transpose().sort_index(), row=3, col=8, resize=False)
Clearly an easy abstraction to be made here, just was a backburner issue.

2023-01-11 23:32 UTC, Bkrenz commented on modules/cogs/droptimizer_cog.py
> +    async def get_droptimizer_boss_list(self, ctx: commands.Context, difficulty: str, search_name: str):
It was originally intended as just bosses, then I realized that since the item strings that make up the index are formatted as 'Boss - Item' it's easy to search for boss or item. Missed renaming the function.

2023-01-11 23:33 UTC, Bkrenz commented on modules/cogs/droptimizer_cog.py
> +            return
Issue with difficulty is it's actually just referencing the like named sheet on the spreadsheet for the raw data. Could solve it by renaming worksheets to lower or some other variety.

2023-01-12 00:38 UTC, Bkrenz commented on modules/cogs/droptimizer_cog.py
> +            return
We can revisit this as a restructuring of the Spreadsheet?

2023-01-12 00:39 UTC, Bkrenz commented on modules/cogs/droptimizer_cog.py
> +            print(e)
ezfix

2023-01-12 00:41 UTC, Bkrenz commented on modules/cogs/droptimizer_cog.py
> +        self.sheets_util.write_data_to_worksheet('Summary', pandas.DataFrame(data=normal_summary).transpose().sort_index(), row=3, col=8, resize=False)
I would suggest if we can, do it as "droptimizer run <difficulty>" with an optional difficulty specifier, and if none is present it just runs all three. Suggestions for a proper abstraction here is appreciated.

2023-01-12 22:42 UTC, Bkrenz commented on blizz_cache.json
> +{"boss": {"-44": "Trash", "2493": "Broodkeeper Diurna", "2499": "Raszageth the Storm-Eater", "2500": "Terros", "2480": "Eranog", "2491": "Kurog Grimtotem", "2482": "Sennarth, the Cold Breath", "2502"
I assume there's a better way to go about caching API results locally that we can use as a standard for every API we use?

2023-01-12 22:43 UTC, Bkrenz commented on modules/utility/blizzard_utility.py
> +            '-44': 'Trash',
-44 is the encounter code for Trash drops, and is not a valid endpoint for the Blizz API. Not sure why it's set up that way.

2023-01-12 23:15 UTC, Bkrenz commented on modules/utility/blizzard_utility.py
> +        self.item_list = cache['item']
Agreed

2023-01-16 11:18 UTC, Bkrenz commented on modules/cogs/droptimizer_cog.py
> +            concat = pandas.concat([max_val, max_item], axis=1)
Dunno that it's *necessary* but not opposed.

2023-02-01 03:21 UTC, merged